/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Skill = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'proficiency' : IDL.Nat,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'offeredSkills' : IDL.Vec(Skill),
  'wantedSkills' : IDL.Vec(Skill),
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'to' : IDL.Principal,
  'content' : IDL.Text,
  'from' : IDL.Principal,
  'timestamp' : Time,
});
export const ExchangeRequest = IDL.Record({
  'to' : IDL.Principal,
  'fromOfferedSkill' : IDL.Text,
  'from' : IDL.Principal,
  'timestamp' : Time,
  'toWantedSkill' : IDL.Text,
  'toOfferedSkill' : IDL.Text,
  'fromWantedSkill' : IDL.Text,
});
export const Rating = IDL.Record({
  'to' : IDL.Principal,
  'review' : IDL.Text,
  'from' : IDL.Principal,
  'timestamp' : Time,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptExchangeRequest' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(Skill), IDL.Vec(Skill)],
      [],
      [],
    ),
  'getAllProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAverageRating' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Float64)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getMyExchangeRequests' : IDL.Func([], [IDL.Vec(ExchangeRequest)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRatings' : IDL.Func([IDL.Principal], [IDL.Vec(Rating)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'leaveRating' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchSkills' : IDL.Func([IDL.Text], [IDL.Vec(Skill)], ['query']),
  'sendExchangeRequest' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Skill = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'proficiency' : IDL.Nat,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'offeredSkills' : IDL.Vec(Skill),
    'wantedSkills' : IDL.Vec(Skill),
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'to' : IDL.Principal,
    'content' : IDL.Text,
    'from' : IDL.Principal,
    'timestamp' : Time,
  });
  const ExchangeRequest = IDL.Record({
    'to' : IDL.Principal,
    'fromOfferedSkill' : IDL.Text,
    'from' : IDL.Principal,
    'timestamp' : Time,
    'toWantedSkill' : IDL.Text,
    'toOfferedSkill' : IDL.Text,
    'fromWantedSkill' : IDL.Text,
  });
  const Rating = IDL.Record({
    'to' : IDL.Principal,
    'review' : IDL.Text,
    'from' : IDL.Principal,
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptExchangeRequest' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(Skill), IDL.Vec(Skill)],
        [],
        [],
      ),
    'getAllProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAverageRating' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getMyExchangeRequests' : IDL.Func(
        [],
        [IDL.Vec(ExchangeRequest)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRatings' : IDL.Func([IDL.Principal], [IDL.Vec(Rating)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'leaveRating' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchSkills' : IDL.Func([IDL.Text], [IDL.Vec(Skill)], ['query']),
    'sendExchangeRequest' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };