/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExchangeRequest {
  'to' : Principal,
  'fromOfferedSkill' : string,
  'from' : Principal,
  'timestamp' : Time,
  'toWantedSkill' : string,
  'toOfferedSkill' : string,
  'fromWantedSkill' : string,
}
export interface Message {
  'to' : Principal,
  'content' : string,
  'from' : Principal,
  'timestamp' : Time,
}
export interface Rating {
  'to' : Principal,
  'review' : string,
  'from' : Principal,
  'timestamp' : Time,
  'rating' : bigint,
}
export interface Skill {
  'name' : string,
  'description' : string,
  'proficiency' : bigint,
  'category' : string,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'offeredSkills' : Array<Skill>,
  'wantedSkills' : Array<Skill>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Accept an exchange request — requires #user role; caller must be the recipient
   */
  'acceptExchangeRequest' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create or update the caller's profile (extended version with individual fields)
   */
  'createOrUpdateProfile' : ActorMethod<
    [string, string, Array<Skill>, Array<Skill>],
    undefined
  >,
  /**
   * / Browse all profiles — public browsing, no auth required
   */
  'getAllProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  /**
   * / Get the average rating for a user — public, no auth required
   */
  'getAverageRating' : ActorMethod<[Principal], [] | [number]>,
  /**
   * / Required by frontend: get the caller's own profile
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get messages with another user — requires #user role AND caller must be a participant
   */
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  /**
   * / Get exchange requests addressed to the caller — requires #user role
   */
  'getMyExchangeRequests' : ActorMethod<[], Array<ExchangeRequest>>,
  /**
   * / Alias kept for backward compatibility — public browsing, no auth required
   */
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Fetch any user's profile — public browsing, no auth required
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Get all ratings received by a user — public, no auth required
   */
  'getUserRatings' : ActorMethod<[Principal], Array<Rating>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Leave a rating for another user — requires #user role
   */
  'leaveRating' : ActorMethod<[Principal, bigint, string], undefined>,
  /**
   * / Required by frontend: save the caller's own profile
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Search offered skills by name or category — public, no auth required
   */
  'searchSkills' : ActorMethod<[string], Array<Skill>>,
  /**
   * / Send an exchange request — requires #user role
   */
  'sendExchangeRequest' : ActorMethod<[Principal, string, string], undefined>,
  /**
   * / Send a message — requires #user role AND an accepted match between caller and toUser
   */
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];